---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sample-domain1-weblogic-credentials
  namespace: weblogic-domain1-ns
spec:
  encryptedData:
    password: AgCA/sEYowJvr1pXoNRH8PQqjtI8Sx02zY64VXCW1gCYsNvQKwr5j5wCTPo4exUceynOKCsNwmJPDR1y5FeCg6Og86Qy1kQQmliglbOp84+2mvuxdsTsD+EKESAVflJinrZOrtpHcX+ElBrlbObrN3FGSWaeOsB7gs2BwHUsWER2vzJkwEmR4vrDoEUWLYducJvkXlANlmyZEh+NLgd7cryDLEwCTxrYM6M3uFb1yHmUBujbPq8tAwsQcl2GExLi9CAkxNqsck72DfYyggOF75muEVPZeqxPZ4+K1o3vur8qmvep1IrnYNzgPcaEOzhdOg0RFPJCtN9S7DyykNSt2uE9VEfKG5Flru7/68TmIB3ulXl3IxBZyvtMwOMXf07IlD4JmbZwDFNPCjkb+6plqtAlw7VizZVF5d/kL4TCx2nHi+Agin96uzulHaobkXgp/QGvUNoAjL45YBOZA2zOP4yFhYRGZYUAJDivSgTTtIZkaf+J0J3+Oj33xapHbkUzSxpEScGqiC9CYtq+w6W880qwJRarUODt0J+NCgnnWH8NRF8lpdSderRfDiFxzOmTToov3FNbaTKWG0T11tp9bZvggF7wXOX2Vvr/oJEEJHjzscWJKX9/W59O1hhqVzqakyffpaiP3cGpL8QuBAOCuaF0YDjpOD1iXjdTNCBaVwM63lYAD1WzdM4feacKMMJYTz7fLxjh3RYN76p5
    username: AgDqsGYBmwzlxsjYuYxFivhJUMeukzfXIAaBm35bNqWIszmMl4/SXP1y4MD6C+Eu71ZnI7y9ZGmpLEhAeRWOx9bAJccl35MFcwUALLQMZotMIumn20RFN0VovRwH61eiw7rbBLzsmv29xEn8XUiT7WmPgi1DHLKPpBtZD7+wUf6NsvfkS/9o07rQAEGwRWldQb2c0zEm5AjTARkf7hAB6sn6mFjwAFhxpwnk2FSQhwX3RqesXf1QhLnuiCDykqcSqmPhB93WItYA041wLGDouO+NtpusrJXshHSiCxTsiJwfUKOL1vSEGEG1drfDEpkFKj+dmm+30aDkVvthIimbTfL4iRVtB5L4E0h0s3q7i1q7qfDwcmPFtrXvTksVwGQObFmfAn2gYAVM0FXa10UI+yotWtZgAQ7CZIRQHhj0ILD/LJxm0xXudc0kx/eUkMR0cMO/rXHI5x+/CPLxnCLMpFS3c4UhkWesu9sSULftRa9JZX0tamCQDJMGNtByP4WeTvFSROsD8d7FdYbpuULVUqQ8odQFMCtx/N33FOxrjtFPFNwk4pfqjkxvy2/LPGA+jvDtNzryHjb9KJ1W6/7p5OVM7Mwkq8rsbj7M6BSMrnPPnzWT+4St5y6kknbCLKSNej7GJFlKBTGDjtuBt+zblOpsaraVsldOMxyg+v3DmX/8i2/TjZG2sYTPiNpj2Cw8t9TiXL9zSO+22Q==
  template:
    metadata:
      name: sample-domain1-weblogic-credentials
      namespace: weblogic-domain1-ns
