---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sample-domain1-runtime-encryption-secret
  namespace: weblogic-domain1-ns
spec:
  encryptedData:
    password: AgBagTqT1wtAXednNG5QTK4/JAv9rbOQ8Ng78JQMoJelzrW3PeqfoHdKUS5YdlKaVxaLUPMJ2V20lgvhDjoaF88hqhkvm+07+plT9LXWqHHBDs1FM1J8tS/HzVtCRmstMy/g5KlWshJ1SdyrFrHASKaRdoXJYrCbL4JAj5oxMnc2OKB5mZXxEwwpTENz5sYYh70xgju12sJRn9e2qWfA8pa6MjVtHelTS5MIqeoQigOpl97x9zXLpZmLViPh+8aP90f6bDaJOVPM0HnbCb9ORoguAeVPyZ3mYnPm8Md24+r+F/zjdeaOsq8rixMeIvg+InC8rRCw9D/85gpRu129fXXS2Y3YWollcBjsc/sx6bUQr9uBwISMYz74FUJ4aIQQwsxIMKUMnl9HxoxkmWXbrCpb4+p4NW5pX9DH687ea26zwqMnzJDYYcFAWfuk1K6YMPkw4AVk2l8QFTqAG6z+rRHVK+jf9qIeMF4LzyLU6kkyvszLAo8Q/AK0gtygIFD3jRFEmjzsGG3aL4Cg6x85rtWNe3X8ww0EovdGjmsTvKC6/BOVWWs52S/nCpbFeOLnrR1PVWgaUJh1NFKYfVR/89E52ElwZq7ilMyDmYGnBfgIGfby+vyTcYXYG4LCaCYPry1vu2ElIhawa04AzaHuq9vu12GNBV5dSJWL1Np0RmhOlt3QwmUzQvsgrhG4QtlrC4G3Q2Uo9tRdy2jZ
  template:
    metadata:
      name: sample-domain1-runtime-encryption-secret
      namespace: weblogic-domain1-ns
