---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sample-domain1-weblogic-credentials
  namespace: weblogic-domain1-ns
spec:
  encryptedData:
    password: AgC/1Anv6ifZSNhP+GQa4eg164dyhZk2hI8FDOMA/BF8v5L+Co4o5gEb80sfYz38qUnK3HCr1EM2DLMlbesemcKQv6JcDmiWKZVL+ymfNoVH2WIRibt2iOHZygBn8C++pWsM1IMmtUoxGpunccekxQad95nzK2L9eKaXFfI+rTR+XVzoSaVIAUds0+KWu2hFQTW88KCqg7f/JYBuDeYQtaryEWRT1gGrcpbMRGk5mZGDgjZnBakJLfZaWQfk3sZoCsA+aBg3lxghmedGe2sdl4dCm8RCzDj/VUluLbprLYtoImmq78PZqoxQGvPelMqvN/qDYD08U2g5znWYy8vHeC96XQhavj0PU20zD0Vi8yxvTaGmHAyY81hLiw58kmUEbtT/1LkW4ZNASbm72u29D74re5Z5tZxmRNI0k4KpsYzWzBqSTgBlbSm9dJ8zM+5+JEK3dABHHvqWwYkUePuQK47zJC6JdoN57yzR2TTnL9dgvtaoHXrv6Ie6Tei3xnylW01FkSdsOoF41wcQzHGAmE0vy5IWvxWJauW3x2OTbE52+DiWWS0klw8KqYFJh3HbYuo7gKhurrQ4wG5EkuRLyhoS92QB05jokIG0sRi4/Y6+5mvERl1k0jjRvo4T8tZQNyvmw5C3ZRbXnD3BUGc0wunJe1/GTKHjboE20PO1n9DUKWMpG5rpcsLOuz8flEasJlZVBY+xTTdMdBE=
    username: AgBYGuX9hRVsFv+xpCtm8qDknUmpFHntpLW8NqiaKJgZHhqkx2ijhqjSRPpBIdhhx5MXcBWcCjhjpYtbCPGQSkrwEQt5vvzuxXrkz401DcwFEpGkP4AF0neWQ7OQ7F9wKiMYekw7PXr+Q2lAojZEfsZDFvwZlxSRD3+AEMLyyduM+TVKdD4xtVNKFM2qz2/7QDAaHdWo19LtEkD1g/70slZPcCIPZxGJ7c3ykpen2mpwdNbzHVekkhhHRAfr+DG6qKchO/2HYdjEw3f2X9OPhMgtSH2DJlFjfvSLZIk+hbaj/0XzkaMFD5CRfEn3iKub76pMZafOvSAXgP0uFo1p2EzPdHvwN1bH8JDFYv/wrzINPU+K5fHJLXIZzdJhNSbQduNdcOj1qBHX22XJiMgtCnpC1raDbikfz7b5oQ3hoYjFBZBdajfsa19BRarRTotn+ggMeo/F6oGkVEiqsljQD1++XDQCvrA7UoXgcWS6wpK0lXyoSG2EbdpyByBD843QBJB/iOEnqNTKHmEMKFoghA642elsFZ0wOl8KQ0F+Nfo425jZEIAke47rYa0tWCeGg3sLj8G8XAO8hYesmuTh284Stnfq7pJnYwUCltaZ+VOfFc6K64fa4enfAy7/v49fkTpNd1/XBJnpQ+GmynZpeMnzNsyhF24d1xM6kJQzzRUguCjoge7gdBcdWJOVDh8Pvv7eyQFbt4UOkQ==
  template:
    metadata:
      name: sample-domain1-weblogic-credentials
      namespace: weblogic-domain1-ns
