---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sample-domain1-runtime-encryption-secret
  namespace: weblogic-domain1-ns
spec:
  encryptedData:
    password: AgB2icQDdrYcrzrg9uLCD93S0wfQIOfGitYjxlK8bgCSgR4NmXV58JDbpriHDd418S7llhPs3YgIEKFkyC+x8+JZxbHVy7qHxraFU4c4LyJeJaQjHUpx5GWl8Xg6TVt0fWBUHrYg+OqGmbtOPP0gYUximBxp3/u5VcAXV52wpkeBUPAlbmvx2XkWIWMUE8qaFmz9fWBLop2Do4NCp847IJS2ChdfDWIdQEVnjVDXHeKPR6AqGx7dwW5nDQPHfHAhocManBAya2/Rz8prFv5rWHFa9KKQ4Lx6WRrrviQixgIFlBCP8lnUO6wONzWZsBLH/Zlf1/TgbMbES2leN6ciK4P5rzq8px+3WHdftq9TRsP4gvfKX5Cxrrsh3Spv91M/nImJewSdF0OFmiSft5u/xiGk2Vn5r1mbEIXREubszbnmub/A3p3a8F3PE9TbbNeQXdBri/y7IbixKr2ukf9BMo1WjLSbOP6k9/JfFsoWIe7ot/rc0uldaikZKCdwmQE6NUFxJhLWwakz7C6Jl2xxik/bnSQbEmPjaZTtp3jqEQZMMBcdt9dcCmfnw737OnC0qFoJuCUqXjhvoWaIFYseT/czwRbnzS8hvmU5ER+iMOzwfaP0hUZG5PBdELQwGvmBrqES372JfVjLxXow/0pAAOoXxCEXitcNW9mUFWx0xd9K+/BJ60qYPJdIbsBbTB9InTzVJasR+0+Dmf0=
  template:
    metadata:
      name: sample-domain1-runtime-encryption-secret
      namespace: weblogic-domain1-ns
